# Generated by Django 3.1 on 2020-09-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenurl',
            name='shortcode',
            field=models.SlugField(blank=True, max_length=15, unique=True),
        ),
    ]
